name: Server-side tests

on:
  push:
    paths:
    - 'server/**'
    - '.github/workflows/server.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    strategy:
      matrix:
        python-version: [3.6, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Add the MariaDB apt repository
      run: |
        wget https://downloads.mariadb.com/MariaDB/mariadb_repo_setup \
          && chmod +x mariadb_repo_setup \
          && sudo ./mariadb_repo_setup \
            --mariadb-server-version="mariadb-10.5" \
          && sudo apt update
    - name: Install apt dependencies
      run: |
        sudo apt-get install libmariadb3 libmariadb-dev
    - name: Install pip dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run pylint
      run: pylint --load-plugins pylint_quotes cultural_touchstones test
