name: Server-side tests

on:
  push:
    paths:
    - 'server/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    strategy:
      matrix:
        python-version: [3.6, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get install \
          mariadb-server \
          mariadb-backup \
          libmariadb3 \
          libmariadb-dev \
          python3-dev
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run pylint
      run: pylint --load-plugins pylint_quotes cultural_touchstones
